//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITLA_PE_MVC.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class BecasJuventud
    {
        public string Email { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string IdentificacionCedula { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Genero { get; set; }
        public string TelResidencial { get; set; }
        public string TelCelular { get; set; }
        public int SolicitudID { get; set; }
        public string Calve { get; set; }
        public Nullable<int> UsuarioID { get; set; }
        public Nullable<int> EstudianteID { get; set; }
    }
}
