
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ITLA_PE_MVC.ENTITY
{

using System;
    using System.Collections.Generic;
    
public partial class GenericType
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public GenericType()
    {

        this.Generics = new HashSet<Generic>();

    }


    public string GenericTypeCode { get; set; }

    public string GenericTypeDescription { get; set; }

    public bool IsUserEditable { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Generic> Generics { get; set; }

}

}
