
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ITLA_PE_MVC.ENTITY
{

using System;
    using System.Collections.Generic;
    
public partial class Generic
{

    public int GenericID { get; set; }

    public string GenericType { get; set; }

    public string GenericDescription { get; set; }

    public Nullable<int> LastLoginSessionID { get; set; }

    public Nullable<System.DateTime> LastUpdateDate { get; set; }

    public bool IsActive { get; set; }

    public Nullable<int> OrderIndex { get; set; }

    public Nullable<decimal> NumericValue { get; set; }



    public virtual GenericType GenericType1 { get; set; }

}

}
