//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITLA_PE_MVC.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class Intencion
    {
        public int IntencionID { get; set; }
        public int CarreraID { get; set; }
        public string CodigoIntencion { get; set; }
        public System.Guid RowID { get; set; }
        public byte[] RowVersion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string Email { get; set; }
        public int GenericID_TipoIdentificacion { get; set; }
        public int GenericID_EstatusIntencion { get; set; }
        public string IdentificacionCedula { get; set; }
        public string IdentificacionGenerada { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string TelResidencial { get; set; }
        public string TelCelular { get; set; }
        public int DireccionidMunicipio { get; set; }
        public string DireccionCalleNumero { get; set; }
        public int GenericID_NivelAcademico { get; set; }
        public string ResultadoComentario { get; set; }
        public Nullable<int> ProvinciaId { get; set; }
        public Nullable<int> Ingreso_Familiar { get; set; }
        public Nullable<bool> TieneInternet { get; set; }
        public Nullable<bool> TieneLaptopPc { get; set; }
        public Nullable<bool> TieneSubsidio { get; set; }
    }
}
