
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ITLA_PE_MVC.ENTITY
{

using System;
    using System.Collections.Generic;
    
public partial class Log
{

    public int Id { get; set; }

    public string LogTypeDesc { get; set; }

    public string LogModule { get; set; }

    public string LogApp { get; set; }

    public string LogMessage { get; set; }

}

}
