//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITLA_PE_MVC.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class MateriaGrupoNuevo
    {
        public int idMateria { get; set; }
        public int iDGrupo { get; set; }
        public Nullable<System.DateTime> FechaCreado { get; set; }
        public string Materia { get; set; }
    }
}
