//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITLA_PE_MVC.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class MJ20201012
    {
        public int ID { get; set; }
        public string C_Form_id { get; set; }
        public string Form_date { get; set; }
        public string Status { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Fecha_de_nacimiento { get; set; }
        public string Tipo_identificacion { get; set; }
        public string No_documento { get; set; }
        public string Celular { get; set; }
        public string Email { get; set; }
        public string Tel_residencial { get; set; }
        public string Con_internet { get; set; }
        public string Con_computadora { get; set; }
        public string Con_solidaridad { get; set; }
        public string Ingreso_familiar { get; set; }
        public string Provincia { get; set; }
        public string Municipio { get; set; }
        public string Direccion { get; set; }
        public string Nivel_completado { get; set; }
        public string Programa_horario { get; set; }
        public string Archivo_cedula { get; set; }
        public string Programa_horario_2 { get; set; }
        public string Referer_page { get; set; }
        public string Archivo_acta_de_nacimiento { get; set; }
        public string Comprobante_de_estudios { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string RazonInvalidez { get; set; }
        public Nullable<int> ProyectoEspecialMateriaGrupoID { get; set; }
        public Nullable<int> ProyectoEspecialMateriaGrupoID2 { get; set; }
        public Nullable<int> GenericID_NivelAcademico { get; set; }
        public Nullable<int> GenericID_TipoIdentificacion { get; set; }
        public Nullable<int> GenericID_Ingreso_Familiar { get; set; }
        public Nullable<int> ProvinciaId { get; set; }
    }
}
