//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITLA_PE_MVC.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrbiServicioEntrega
    {
        public int ServicioEntregaId { get; set; }
        public int IDfactura { get; set; }
        public int IDUsuario { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaEntrega { get; set; }
        public string Comentario { get; set; }
    }
}
