//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITLA_PE_MVC.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProyectoEspecialMateriaGrupoSolicitud20201015
    {
        public int ProyectoEspecialMateriaGrupoSolicitudID { get; set; }
        public int ProyectoEspecialMateriaGrupoID { get; set; }
        public int SolicitudID { get; set; }
        public Nullable<int> CupoNumero { get; set; }
    }
}
