
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ITLA_PE_MVC.ENTITY
{

using System;
    using System.Collections.Generic;
    
public partial class ProyectoEspecialMateriaGrupo
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ProyectoEspecialMateriaGrupo()
    {

        this.Solicituds = new HashSet<Solicitud>();

    }


    public int ProyectoEspecialMateriaGrupoID { get; set; }

    public int ProyectoEspecialID { get; set; }

    public int idMateria { get; set; }

    public int idGrupo { get; set; }

    public bool isActive { get; set; }

    public int SolicitanteCupo { get; set; }

    public int SolicitanteCantidad { get; set; }

    public int AprobacionCupo { get; set; }

    public int AprobacionCantidad { get; set; }

    public string MateriaDescripcion { get; set; }



    public virtual ProyectoEspecial ProyectoEspecial { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Solicitud> Solicituds { get; set; }

}

}
