//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITLA_PE_MVC.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReporteGSuit
    {
        public int IDregistro { get; set; }
        public string Fecha { get; set; }
        public string Nombre_evento { get; set; }
        public string Descripcion_evento { get; set; }
        public string Codigo_reunion { get; set; }
        public string Identificador_participante { get; set; }
        public string Participante_ajeno_organizacion { get; set; }
        public string Tipo_cliente { get; set; }
        public string Correoelectronico_organizador { get; set; }
        public string Tipo_producto { get; set; }
        public Nullable<int> Duracion { get; set; }
        public string Valoracion_llamada { get; set; }
        public string Nombre_participante { get; set; }
        public string DireccionIP { get; set; }
        public string Ciudad { get; set; }
        public string Pais { get; set; }
        public string TiempoMedioIdaVuelta { get; set; }
        public string Protocolo_transporte { get; set; }
        public string Ancho_banda_subida { get; set; }
        public string Ancho_banda_descarga { get; set; }
        public string Perdida_maxima_audio { get; set; }
        public string Perdida_media_audio { get; set; }
        public string Duracion_audio { get; set; }
        public string Promedio_audio_enviado { get; set; }
        public string Perdida_paquetes_audio { get; set; }
        public string Perdida_paquetes_audio2 { get; set; }
        public string Duracion_envio_audio { get; set; }
        public string ID_Evento_Calendario { get; set; }
        public string ID_conferencia { get; set; }
        public string Fluctuacion_media { get; set; }
        public string Fluctuacion_maxima { get; set; }
        public string Fluctuacion_media2 { get; set; }
        public string Promedio_pantallas_video { get; set; }
        public string Promedio_fotogramas_video { get; set; }
        public string Mediana_capturas_pantalla { get; set; }
        public string Perdida_maxima_paquetes { get; set; }
        public string Perdida_media_paquetes { get; set; }
        public string Duracion_capturas_pantalla { get; set; }
        public string Mediana_capturas_video { get; set; }
        public string Promedio_capturas_video { get; set; }
        public string Promedio_fotogramas { get; set; }
        public string Promedio_lado_largo { get; set; }
        public string Perdida_Maxima1 { get; set; }
        public string Perdida_media3 { get; set; }
        public string Duracion_capturas { get; set; }
        public string Mediana_corto_capturas { get; set; }
        public string Promedio_fotogramas2 { get; set; }
        public string Mediana_video2 { get; set; }
        public string Perdida_video2 { get; set; }
        public string Perdida_media2 { get; set; }
        public string Duracion_recepcion_video { get; set; }
        public string Mediana_lado_corto1 { get; set; }
        public string Indice_congestion { get; set; }
        public string Promedio_tasa_enviado { get; set; }
        public string Promedio_fotogramas3 { get; set; }
        public string Mediana_lado_largo { get; set; }
        public string Perdida_maxima { get; set; }
        public string Perdida_media4 { get; set; }
        public string Duracion_envio_video { get; set; }
        public string Mediana_lado_corto { get; set; }
        public string Motivo_accion { get; set; }
        public string Descripcion_accion { get; set; }
        public string Nombres_visibles { get; set; }
        public string Correoelectronico_objetivo { get; set; }
        public string Numerotelefono_objetivo { get; set; }
    }
}
