//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITLA_PE_MVC.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int SettingID { get; set; }
        public int DaysToAskForNewPassword { get; set; }
        public string MailServer { get; set; }
        public string MailAccount { get; set; }
        public string MailPassword { get; set; }
        public string MailPort { get; set; }
        public string MailFrom { get; set; }
        public string MailDomain { get; set; }
    }
}
