
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ITLA_PE_MVC.ENTITY
{

using System;
    using System.Collections.Generic;
    
public partial class SystemAttribute
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public SystemAttribute()
    {

        this.UsertTypeSystemAttributes = new HashSet<UsertTypeSystemAttribute>();

    }


    public int SystemAttributeID { get; set; }

    public string AttributeName { get; set; }

    public bool IsPageType { get; set; }

    public string PageUrl { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UsertTypeSystemAttribute> UsertTypeSystemAttributes { get; set; }

}

}
