//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITLA_PE_MVC.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEETLOGDOCENTE
    {
        public int IdRegistro { get; set; }
        public string Fecha { get; set; }
        public string Nombre_evento { get; set; }
        public string Descripcion_evento { get; set; }
        public string Codigo_reunion { get; set; }
        public string Identificador_participante { get; set; }
        public string Participante_ajeno_organizacion { get; set; }
        public string Tipo_cliente { get; set; }
        public string Correoelectronico_organizador { get; set; }
        public string Tipo_producto { get; set; }
        public Nullable<int> Duracion { get; set; }
        public string Valoracion_llamada { get; set; }
        public string Nombre_participante { get; set; }
        public string Direccion_IP { get; set; }
        public string Ciudad { get; set; }
        public string Pais { get; set; }
        public Nullable<int> Tiempo_medio_ida_vuelta_red { get; set; }
        public string Protocolo_transporte { get; set; }
        public string Ancho_banda_subida { get; set; }
        public string Ancho_banda_descarga { get; set; }
        public string Perdida_maxima_paquetes_audio_recibido { get; set; }
        public string Perdida_media_paquetes_audio_recibido { get; set; }
        public string Duracion_recepcion_audio { get; set; }
        public string Promedio_tasa_bits_audio_enviado { get; set; }
        public string Perdida_maxima_paquetes_audio_enviado { get; set; }
        public string Perdida_media_paquetes_audio_enviado { get; set; }
        public string Duracion_envio_audio { get; set; }
        public string ID_evento_calendario { get; set; }
        public string ID_conferencia { get; set; }
        public Nullable<int> Fluctuacion_media_recepcion_red { get; set; }
        public Nullable<int> Maxima_fluctuacion_recepcion_red { get; set; }
        public string Fluctuacion_media_envio_red { get; set; }
        public Nullable<int> Promedio_tasa_bits_capturas_pantalla_video_recibidas { get; set; }
        public string Promedio_otogramas_capturas_pantalla_vídeo_recibidas { get; set; }
        public Nullable<int> Mediana_lado_largo_capturas_pantalla_video_recibidas { get; set; }
        public string Perdida_maxima_paquetes__capturas_pantalla_video_recibidas { get; set; }
        public string Perdida_media_paquetes_capturas_pantalla_video_recibidas { get; set; }
        public string Duracion_recepcion_capturas_pantalla_video { get; set; }
        public Nullable<int> Mediana_lado_corto_capturas_de_pantalla_video_recibidas { get; set; }
        public string Promedio_capturas_pantalla_video_enviadas { get; set; }
        public string Promedio_fotogramas_pantalla_video_enviadas { get; set; }
        public string Promedio_lado_largo_capturas_pantalla_de_video { get; set; }
        public string Perdida_maxima_paquetes_capturas_de_pantalla_de_video_enviadas { get; set; }
        public string Perdida_media_paquetes_capturas_pantalla_video_enviadas { get; set; }
        public string Duracion_capturas_pantalla_video_enviadas { get; set; }
        public string Mediana_lado_corto_capturas_pantalla_video_enviadas { get; set; }
        public string Promedio_fotogramas_video_recibido { get; set; }
        public Nullable<int> Mediana_lado_largo_video_recibido { get; set; }
        public string Perdida_maxima_paquetes_video_recibido { get; set; }
        public string Perdida_media_paquetes_video_recibido { get; set; }
        public string Duracion_recepcion_video { get; set; }
        public Nullable<int> Mediana_lado_corto_video_recibido { get; set; }
        public string Indice_congestion_red { get; set; }
        public string Promedio_tasa_bits_video_enviado { get; set; }
        public string Promedio_fotogramas_video_enviado { get; set; }
        public Nullable<int> Mediana_lado_largo_video_enviado { get; set; }
        public string Perdida_maxima_paquetes_video_enviado { get; set; }
        public string Perdida_media_paquetes_video_enviado { get; set; }
        public string Duracion_envio_video { get; set; }
        public Nullable<int> Mediana_lado_corto_video_enviado { get; set; }
        public string Motivo_accion { get; set; }
        public string Descripcion_accion { get; set; }
        public string Nombres_visibles_objetivo { get; set; }
        public string Correoelectronico_objetivo { get; set; }
        public string Numero_telefono_objetivo { get; set; }
    }
}
