//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITLA_PE_MVC.DATA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using ITLA_PE_MVC.ENTITY;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ORBIPEEntities : DbContext
    {
        public ORBIPEEntities()
            : base("name=ORBIPEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<Generic> Generics { get; set; }
        public virtual DbSet<GenericType> GenericTypes { get; set; }
        public virtual DbSet<Intencion> Intencions { get; set; }
        public virtual DbSet<ProyectoEspecial> ProyectoEspecials { get; set; }
        public virtual DbSet<ProyectoEspecialMateriaGrupo> ProyectoEspecialMateriaGrupoes { get; set; }
        public virtual DbSet<Solicitud> Solicituds { get; set; }
        public virtual DbSet<SolicitudAnexo> SolicitudAnexoes { get; set; }
        public virtual DbSet<LoginSession> LoginSessions { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<SystemAttribute> SystemAttributes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserAction> UserActions { get; set; }
        public virtual DbSet<UserLog> UserLogs { get; set; }
        public virtual DbSet<UsertTypeSystemAttribute> UsertTypeSystemAttributes { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<MeetLogDocente> MeetLogDocentes { get; set; }
    
        public virtual ObjectResult<GetMateriasDisponibles_Result> GetMateriasDisponibles()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetMateriasDisponibles_Result>("GetMateriasDisponibles");
        }
    
        public virtual ObjectResult<UspGenericItems_Result> UspGenericItems(string genericType)
        {
            var genericTypeParameter = genericType != null ?
                new ObjectParameter("GenericType", genericType) :
                new ObjectParameter("GenericType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGenericItems_Result>("UspGenericItems", genericTypeParameter);
        }
    
        public virtual int UspInsertaMateriasGrupoJuventud()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UspInsertaMateriasGrupoJuventud");
        }
    
        public virtual ObjectResult<UspMunicipiosPorProvincia_Result> UspMunicipiosPorProvincia(Nullable<int> idProvincia)
        {
            var idProvinciaParameter = idProvincia.HasValue ?
                new ObjectParameter("IdProvincia", idProvincia) :
                new ObjectParameter("IdProvincia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspMunicipiosPorProvincia_Result>("UspMunicipiosPorProvincia", idProvinciaParameter);
        }
    
        public virtual ObjectResult<UspProvinciasRD_Result> UspProvinciasRD()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspProvinciasRD_Result>("UspProvinciasRD");
        }
    
        public virtual ObjectResult<UspGetDashboardITLAJVMateria_Result> UspGetDashboardITLAJVMateria()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetDashboardITLAJVMateria_Result>("UspGetDashboardITLAJVMateria");
        }
    
        public virtual ObjectResult<UspGetDashboardITLAJVProvincia_Result> UspGetDashboardITLAJVProvincia()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetDashboardITLAJVProvincia_Result>("UspGetDashboardITLAJVProvincia");
        }
    
        public virtual ObjectResult<UspGetLoginInfo_Result> UspGetLoginInfo(string nombreUsuario)
        {
            var nombreUsuarioParameter = nombreUsuario != null ?
                new ObjectParameter("NombreUsuario", nombreUsuario) :
                new ObjectParameter("NombreUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetLoginInfo_Result>("UspGetLoginInfo", nombreUsuarioParameter);
        }
    
        public virtual ObjectResult<UspGetDashboardITLAJVDia_Result> UspGetDashboardITLAJVDia()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetDashboardITLAJVDia_Result>("UspGetDashboardITLAJVDia");
        }
    
        public virtual ObjectResult<UspGetCarrera_Result> UspGetCarrera()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetCarrera_Result>("UspGetCarrera");
        }
    
        public virtual ObjectResult<Nullable<int>> UspGetNextSolicitud()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("UspGetNextSolicitud");
        }
    
        public virtual ObjectResult<UspGetDashboardITLAJVEdad_Result> UspGetDashboardITLAJVEdad()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetDashboardITLAJVEdad_Result>("UspGetDashboardITLAJVEdad");
        }
    
        public virtual ObjectResult<UspGetDashboardITLAJVIngresos_Result> UspGetDashboardITLAJVIngresos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetDashboardITLAJVIngresos_Result>("UspGetDashboardITLAJVIngresos");
        }
    
        public virtual ObjectResult<Nullable<int>> DashboardGeneralINfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("DashboardGeneralINfo");
        }
    
        public virtual ObjectResult<UspGetDashboardIntencionProvincia_Result> UspGetDashboardIntencionProvincia()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetDashboardIntencionProvincia_Result>("UspGetDashboardIntencionProvincia");
        }
    
        public virtual ObjectResult<UspGetDashboardIntencionEdad_Result> UspGetDashboardIntencionEdad()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetDashboardIntencionEdad_Result>("UspGetDashboardIntencionEdad");
        }
    
        public virtual ObjectResult<UspGetDashboardIntencionIngresos_Result> UspGetDashboardIntencionIngresos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetDashboardIntencionIngresos_Result>("UspGetDashboardIntencionIngresos");
        }
    
        public virtual ObjectResult<UspGetDashboardIntencionArea_Result> UspGetDashboardIntencionArea()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetDashboardIntencionArea_Result>("UspGetDashboardIntencionArea");
        }
    
        public virtual ObjectResult<UspGetDashboardIntencionDia_Result> UspGetDashboardIntencionDia()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetDashboardIntencionDia_Result>("UspGetDashboardIntencionDia");
        }
    
        public virtual int Reporte_Inscritos_Seleccion_Cuatrimestre_Any(Nullable<int> idPeriodo)
        {
            var idPeriodoParameter = idPeriodo.HasValue ?
                new ObjectParameter("idPeriodo", idPeriodo) :
                new ObjectParameter("idPeriodo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Reporte_Inscritos_Seleccion_Cuatrimestre_Any", idPeriodoParameter);
        }
    
        public virtual ObjectResult<Reporte_Inscritos_Seleccion_XCarrera_Cuatrimestre_Any_Result> Reporte_Inscritos_Seleccion_XCarrera_Cuatrimestre_Any(Nullable<int> idPeriodo)
        {
            var idPeriodoParameter = idPeriodo.HasValue ?
                new ObjectParameter("idPeriodo", idPeriodo) :
                new ObjectParameter("idPeriodo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Reporte_Inscritos_Seleccion_XCarrera_Cuatrimestre_Any_Result>("Reporte_Inscritos_Seleccion_XCarrera_Cuatrimestre_Any", idPeriodoParameter);
        }
    
        public virtual int Reporte_Inscritos_Seleccion_XFecha_Cuatrimestre_Any(Nullable<int> idPeriodo)
        {
            var idPeriodoParameter = idPeriodo.HasValue ?
                new ObjectParameter("idPeriodo", idPeriodo) :
                new ObjectParameter("idPeriodo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Reporte_Inscritos_Seleccion_XFecha_Cuatrimestre_Any", idPeriodoParameter);
        }
    
        public virtual ObjectResult<UspReporteInscritosSeleccionXCarreraCuatrimestre_Result> UspReporteInscritosSeleccionXCarreraCuatrimestre(Nullable<int> idPeriodo)
        {
            var idPeriodoParameter = idPeriodo.HasValue ?
                new ObjectParameter("idPeriodo", idPeriodo) :
                new ObjectParameter("idPeriodo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspReporteInscritosSeleccionXCarreraCuatrimestre_Result>("UspReporteInscritosSeleccionXCarreraCuatrimestre", idPeriodoParameter);
        }
    
        public virtual ObjectResult<UspReporteInscritosSeleccionXFecha_Result> UspReporteInscritosSeleccionXFecha(Nullable<int> idPeriodo)
        {
            var idPeriodoParameter = idPeriodo.HasValue ?
                new ObjectParameter("idPeriodo", idPeriodo) :
                new ObjectParameter("idPeriodo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspReporteInscritosSeleccionXFecha_Result>("UspReporteInscritosSeleccionXFecha", idPeriodoParameter);
        }
    
        public virtual ObjectResult<UspReporteInscritosSeleccionCuatrimestre_Result> UspReporteInscritosSeleccionCuatrimestre(Nullable<int> idPeriodo)
        {
            var idPeriodoParameter = idPeriodo.HasValue ?
                new ObjectParameter("idPeriodo", idPeriodo) :
                new ObjectParameter("idPeriodo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspReporteInscritosSeleccionCuatrimestre_Result>("UspReporteInscritosSeleccionCuatrimestre", idPeriodoParameter);
        }
    
        public virtual ObjectResult<UspGetDashboardITLAJVEducacion_Result> UspGetDashboardITLAJVEducacion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetDashboardITLAJVEducacion_Result>("UspGetDashboardITLAJVEducacion");
        }
    
        public virtual ObjectResult<UspGetDashboardITLAJVGenero_Result> UspGetDashboardITLAJVGenero()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetDashboardITLAJVGenero_Result>("UspGetDashboardITLAJVGenero");
        }
    
        public virtual ObjectResult<UspGetPeriodo_Result> UspGetPeriodo(Nullable<int> idperiodo)
        {
            var idperiodoParameter = idperiodo.HasValue ?
                new ObjectParameter("Idperiodo", idperiodo) :
                new ObjectParameter("Idperiodo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetPeriodo_Result>("UspGetPeriodo", idperiodoParameter);
        }
    
        public virtual ObjectResult<UspGetDashboardIntencionEducacion_Result> UspGetDashboardIntencionEducacion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetDashboardIntencionEducacion_Result>("UspGetDashboardIntencionEducacion");
        }
    
        public virtual ObjectResult<UspGetDashboardIntencionINTERNET_Result> UspGetDashboardIntencionINTERNET()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetDashboardIntencionINTERNET_Result>("UspGetDashboardIntencionINTERNET");
        }
    
        public virtual ObjectResult<UspGetDashboardIntencionPC_Result> UspGetDashboardIntencionPC()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetDashboardIntencionPC_Result>("UspGetDashboardIntencionPC");
        }
    
        public virtual ObjectResult<UspReporteIntencion_Result> UspReporteIntencion(Nullable<System.DateTime> dateFROM, Nullable<System.DateTime> dateTo)
        {
            var dateFROMParameter = dateFROM.HasValue ?
                new ObjectParameter("DateFROM", dateFROM) :
                new ObjectParameter("DateFROM", typeof(System.DateTime));
    
            var dateToParameter = dateTo.HasValue ?
                new ObjectParameter("DateTo", dateTo) :
                new ObjectParameter("DateTo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspReporteIntencion_Result>("UspReporteIntencion", dateFROMParameter, dateToParameter);
        }
    
        public virtual ObjectResult<DashboardGeneroPorPeriodo_Result> DashboardGeneroPorPeriodo(Nullable<int> iDperiodo)
        {
            var iDperiodoParameter = iDperiodo.HasValue ?
                new ObjectParameter("IDperiodo", iDperiodo) :
                new ObjectParameter("IDperiodo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DashboardGeneroPorPeriodo_Result>("DashboardGeneroPorPeriodo", iDperiodoParameter);
        }
    
        public virtual ObjectResult<DashboardRangoEdadPorPeriodo_Result> DashboardRangoEdadPorPeriodo(Nullable<int> iDperiodo)
        {
            var iDperiodoParameter = iDperiodo.HasValue ?
                new ObjectParameter("IDperiodo", iDperiodo) :
                new ObjectParameter("IDperiodo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DashboardRangoEdadPorPeriodo_Result>("DashboardRangoEdadPorPeriodo", iDperiodoParameter);
        }
    }
}
