//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITLA_PE_MVC.DATA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using ITLA_PE_MVC.ENTITY;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ORBIPEEntities : DbContext
    {
        public ORBIPEEntities()
            : base("name=ORBIPEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<Generic> Generics { get; set; }
        public virtual DbSet<GenericType> GenericTypes { get; set; }
        public virtual DbSet<Intencion> Intencions { get; set; }
        public virtual DbSet<ProyectoEspecial> ProyectoEspecials { get; set; }
        public virtual DbSet<ProyectoEspecialMateriaGrupo> ProyectoEspecialMateriaGrupoes { get; set; }
        public virtual DbSet<Solicitud> Solicituds { get; set; }
        public virtual DbSet<SolicitudAnexo> SolicitudAnexoes { get; set; }
        public virtual DbSet<LoginSession> LoginSessions { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<SystemAttribute> SystemAttributes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserAction> UserActions { get; set; }
        public virtual DbSet<UserLog> UserLogs { get; set; }
        public virtual DbSet<UsertTypeSystemAttribute> UsertTypeSystemAttributes { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<MateriaGrupoNuevo> MateriaGrupoNuevoes { get; set; }
        public virtual DbSet<ProyectoEspecialMateriaGrupoSolicitud> ProyectoEspecialMateriaGrupoSolicituds { get; set; }
        public virtual DbSet<OrbiServicioEntrega> OrbiServicioEntregas { get; set; }
        public virtual DbSet<CartaAdmision> CartaAdmisions { get; set; }
    
        public virtual ObjectResult<GetMateriasDisponibles_Result> GetMateriasDisponibles()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetMateriasDisponibles_Result>("GetMateriasDisponibles");
        }
    
        public virtual ObjectResult<UspGenericItems_Result> UspGenericItems(string genericType)
        {
            var genericTypeParameter = genericType != null ?
                new ObjectParameter("GenericType", genericType) :
                new ObjectParameter("GenericType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGenericItems_Result>("UspGenericItems", genericTypeParameter);
        }
    
        public virtual int UspInsertaMateriasGrupoJuventud()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UspInsertaMateriasGrupoJuventud");
        }
    
        public virtual ObjectResult<UspMunicipiosPorProvincia_Result> UspMunicipiosPorProvincia(Nullable<int> idProvincia)
        {
            var idProvinciaParameter = idProvincia.HasValue ?
                new ObjectParameter("IdProvincia", idProvincia) :
                new ObjectParameter("IdProvincia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspMunicipiosPorProvincia_Result>("UspMunicipiosPorProvincia", idProvinciaParameter);
        }
    
        public virtual ObjectResult<UspProvinciasRD_Result> UspProvinciasRD()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspProvinciasRD_Result>("UspProvinciasRD");
        }
    
        public virtual ObjectResult<UspGetDashboardITLAJVMateria_Result> UspGetDashboardITLAJVMateria()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetDashboardITLAJVMateria_Result>("UspGetDashboardITLAJVMateria");
        }
    
        public virtual ObjectResult<UspGetDashboardITLAJVProvincia_Result> UspGetDashboardITLAJVProvincia()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetDashboardITLAJVProvincia_Result>("UspGetDashboardITLAJVProvincia");
        }
    
        public virtual ObjectResult<UspGetLoginInfo_Result> UspGetLoginInfo(string nombreUsuario)
        {
            var nombreUsuarioParameter = nombreUsuario != null ?
                new ObjectParameter("NombreUsuario", nombreUsuario) :
                new ObjectParameter("NombreUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetLoginInfo_Result>("UspGetLoginInfo", nombreUsuarioParameter);
        }
    
        public virtual ObjectResult<UspGetDashboardITLAJVDia_Result> UspGetDashboardITLAJVDia()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetDashboardITLAJVDia_Result>("UspGetDashboardITLAJVDia");
        }
    
        public virtual ObjectResult<UspGetCarrera_Result> UspGetCarrera()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetCarrera_Result>("UspGetCarrera");
        }
    
        public virtual ObjectResult<Nullable<int>> UspGetNextSolicitud()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("UspGetNextSolicitud");
        }
    
        public virtual ObjectResult<UspGetDashboardITLAJVEdad_Result> UspGetDashboardITLAJVEdad()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetDashboardITLAJVEdad_Result>("UspGetDashboardITLAJVEdad");
        }
    
        public virtual ObjectResult<UspGetDashboardITLAJVIngresos_Result> UspGetDashboardITLAJVIngresos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetDashboardITLAJVIngresos_Result>("UspGetDashboardITLAJVIngresos");
        }
    
        public virtual ObjectResult<Nullable<int>> DashboardGeneralINfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("DashboardGeneralINfo");
        }
    
        public virtual ObjectResult<UspGetDashboardIntencionProvincia_Result> UspGetDashboardIntencionProvincia()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetDashboardIntencionProvincia_Result>("UspGetDashboardIntencionProvincia");
        }
    
        public virtual ObjectResult<UspGetDashboardIntencionEdad_Result> UspGetDashboardIntencionEdad()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetDashboardIntencionEdad_Result>("UspGetDashboardIntencionEdad");
        }
    
        public virtual ObjectResult<UspGetDashboardIntencionIngresos_Result> UspGetDashboardIntencionIngresos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetDashboardIntencionIngresos_Result>("UspGetDashboardIntencionIngresos");
        }
    
        public virtual ObjectResult<UspGetDashboardIntencionArea_Result> UspGetDashboardIntencionArea()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetDashboardIntencionArea_Result>("UspGetDashboardIntencionArea");
        }
    
        public virtual ObjectResult<UspGetDashboardIntencionDia_Result> UspGetDashboardIntencionDia()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetDashboardIntencionDia_Result>("UspGetDashboardIntencionDia");
        }
    
        public virtual int Reporte_Inscritos_Seleccion_Cuatrimestre_Any(Nullable<int> idPeriodo)
        {
            var idPeriodoParameter = idPeriodo.HasValue ?
                new ObjectParameter("idPeriodo", idPeriodo) :
                new ObjectParameter("idPeriodo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Reporte_Inscritos_Seleccion_Cuatrimestre_Any", idPeriodoParameter);
        }
    
        public virtual ObjectResult<Reporte_Inscritos_Seleccion_XCarrera_Cuatrimestre_Any_Result> Reporte_Inscritos_Seleccion_XCarrera_Cuatrimestre_Any(Nullable<int> idPeriodo)
        {
            var idPeriodoParameter = idPeriodo.HasValue ?
                new ObjectParameter("idPeriodo", idPeriodo) :
                new ObjectParameter("idPeriodo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Reporte_Inscritos_Seleccion_XCarrera_Cuatrimestre_Any_Result>("Reporte_Inscritos_Seleccion_XCarrera_Cuatrimestre_Any", idPeriodoParameter);
        }
    
        public virtual int Reporte_Inscritos_Seleccion_XFecha_Cuatrimestre_Any(Nullable<int> idPeriodo)
        {
            var idPeriodoParameter = idPeriodo.HasValue ?
                new ObjectParameter("idPeriodo", idPeriodo) :
                new ObjectParameter("idPeriodo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Reporte_Inscritos_Seleccion_XFecha_Cuatrimestre_Any", idPeriodoParameter);
        }
    
        public virtual ObjectResult<UspReporteInscritosSeleccionXCarreraCuatrimestre_Result> UspReporteInscritosSeleccionXCarreraCuatrimestre(Nullable<int> idPeriodo)
        {
            var idPeriodoParameter = idPeriodo.HasValue ?
                new ObjectParameter("idPeriodo", idPeriodo) :
                new ObjectParameter("idPeriodo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspReporteInscritosSeleccionXCarreraCuatrimestre_Result>("UspReporteInscritosSeleccionXCarreraCuatrimestre", idPeriodoParameter);
        }
    
        public virtual ObjectResult<UspReporteInscritosSeleccionXFecha_Result> UspReporteInscritosSeleccionXFecha(Nullable<int> idPeriodo)
        {
            var idPeriodoParameter = idPeriodo.HasValue ?
                new ObjectParameter("idPeriodo", idPeriodo) :
                new ObjectParameter("idPeriodo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspReporteInscritosSeleccionXFecha_Result>("UspReporteInscritosSeleccionXFecha", idPeriodoParameter);
        }
    
        public virtual ObjectResult<UspReporteInscritosSeleccionCuatrimestre_Result> UspReporteInscritosSeleccionCuatrimestre(Nullable<int> idPeriodo)
        {
            var idPeriodoParameter = idPeriodo.HasValue ?
                new ObjectParameter("idPeriodo", idPeriodo) :
                new ObjectParameter("idPeriodo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspReporteInscritosSeleccionCuatrimestre_Result>("UspReporteInscritosSeleccionCuatrimestre", idPeriodoParameter);
        }
    
        public virtual ObjectResult<UspGetDashboardITLAJVEducacion_Result> UspGetDashboardITLAJVEducacion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetDashboardITLAJVEducacion_Result>("UspGetDashboardITLAJVEducacion");
        }
    
        public virtual ObjectResult<UspGetDashboardITLAJVGenero_Result> UspGetDashboardITLAJVGenero()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetDashboardITLAJVGenero_Result>("UspGetDashboardITLAJVGenero");
        }
    
        public virtual ObjectResult<UspGetPeriodo_Result> UspGetPeriodo(Nullable<int> idRecinto, string n_corto, Nullable<int> tipoPeriodo, Nullable<int> naturaleza)
        {
            var idRecintoParameter = idRecinto.HasValue ?
                new ObjectParameter("idRecinto", idRecinto) :
                new ObjectParameter("idRecinto", typeof(int));
    
            var n_cortoParameter = n_corto != null ?
                new ObjectParameter("n_corto", n_corto) :
                new ObjectParameter("n_corto", typeof(string));
    
            var tipoPeriodoParameter = tipoPeriodo.HasValue ?
                new ObjectParameter("tipoPeriodo", tipoPeriodo) :
                new ObjectParameter("tipoPeriodo", typeof(int));
    
            var naturalezaParameter = naturaleza.HasValue ?
                new ObjectParameter("naturaleza", naturaleza) :
                new ObjectParameter("naturaleza", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetPeriodo_Result>("UspGetPeriodo", idRecintoParameter, n_cortoParameter, tipoPeriodoParameter, naturalezaParameter);
        }
    
        public virtual ObjectResult<UspGetDashboardIntencionEducacion_Result> UspGetDashboardIntencionEducacion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetDashboardIntencionEducacion_Result>("UspGetDashboardIntencionEducacion");
        }
    
        public virtual ObjectResult<UspGetDashboardIntencionINTERNET_Result> UspGetDashboardIntencionINTERNET()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetDashboardIntencionINTERNET_Result>("UspGetDashboardIntencionINTERNET");
        }
    
        public virtual ObjectResult<UspGetDashboardIntencionPC_Result> UspGetDashboardIntencionPC()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetDashboardIntencionPC_Result>("UspGetDashboardIntencionPC");
        }
    
        public virtual ObjectResult<UspReporteIntencion_Result> UspReporteIntencion(Nullable<System.DateTime> dateFROM, Nullable<System.DateTime> dateTo)
        {
            var dateFROMParameter = dateFROM.HasValue ?
                new ObjectParameter("DateFROM", dateFROM) :
                new ObjectParameter("DateFROM", typeof(System.DateTime));
    
            var dateToParameter = dateTo.HasValue ?
                new ObjectParameter("DateTo", dateTo) :
                new ObjectParameter("DateTo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspReporteIntencion_Result>("UspReporteIntencion", dateFROMParameter, dateToParameter);
        }
    
        public virtual ObjectResult<DashboardGeneroPorPeriodo_Result> DashboardGeneroPorPeriodo(Nullable<int> iDperiodo)
        {
            var iDperiodoParameter = iDperiodo.HasValue ?
                new ObjectParameter("IDperiodo", iDperiodo) :
                new ObjectParameter("IDperiodo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DashboardGeneroPorPeriodo_Result>("DashboardGeneroPorPeriodo", iDperiodoParameter);
        }
    
        public virtual ObjectResult<DashboardRangoEdadPorPeriodo_Result> DashboardRangoEdadPorPeriodo(Nullable<int> iDperiodo)
        {
            var iDperiodoParameter = iDperiodo.HasValue ?
                new ObjectParameter("IDperiodo", iDperiodo) :
                new ObjectParameter("IDperiodo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DashboardRangoEdadPorPeriodo_Result>("DashboardRangoEdadPorPeriodo", iDperiodoParameter);
        }
    
        public virtual ObjectResult<UspGetDashboardAdmisionCarrera_Result> UspGetDashboardAdmisionCarrera()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetDashboardAdmisionCarrera_Result>("UspGetDashboardAdmisionCarrera");
        }
    
        public virtual ObjectResult<UspGetDashboardAdmisionCosteo_Result> UspGetDashboardAdmisionCosteo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetDashboardAdmisionCosteo_Result>("UspGetDashboardAdmisionCosteo");
        }
    
        public virtual ObjectResult<UspGetDashboardAdmisionEdad_Result> UspGetDashboardAdmisionEdad()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetDashboardAdmisionEdad_Result>("UspGetDashboardAdmisionEdad");
        }
    
        public virtual ObjectResult<UspGetDashboardAdmisionFecha_Result> UspGetDashboardAdmisionFecha()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetDashboardAdmisionFecha_Result>("UspGetDashboardAdmisionFecha");
        }
    
        public virtual ObjectResult<UspGetDashboardAdmisionGenero_Result> UspGetDashboardAdmisionGenero()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetDashboardAdmisionGenero_Result>("UspGetDashboardAdmisionGenero");
        }
    
        public virtual ObjectResult<UspGetDashboardAdmisionInfo_Result> UspGetDashboardAdmisionInfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetDashboardAdmisionInfo_Result>("UspGetDashboardAdmisionInfo");
        }
    
        public virtual ObjectResult<UspGetDashboardAdmisionIngresos_Result> UspGetDashboardAdmisionIngresos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetDashboardAdmisionIngresos_Result>("UspGetDashboardAdmisionIngresos");
        }
    
        public virtual ObjectResult<UspGetDashboardAdmisionPeriodoIngreso_Result> UspGetDashboardAdmisionPeriodoIngreso()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetDashboardAdmisionPeriodoIngreso_Result>("UspGetDashboardAdmisionPeriodoIngreso");
        }
    
        public virtual ObjectResult<UspGetDashboardAdmisionProvincia_Result> UspGetDashboardAdmisionProvincia()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetDashboardAdmisionProvincia_Result>("UspGetDashboardAdmisionProvincia");
        }
    
        public virtual ObjectResult<UspGetDashboardAdmisionTanda_Result> UspGetDashboardAdmisionTanda()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetDashboardAdmisionTanda_Result>("UspGetDashboardAdmisionTanda");
        }
    
        public virtual ObjectResult<UspGetDashboardAdmisionTipoSolicitud_Result> UspGetDashboardAdmisionTipoSolicitud()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetDashboardAdmisionTipoSolicitud_Result>("UspGetDashboardAdmisionTipoSolicitud");
        }
    
        public virtual ObjectResult<UspGetDashboardAdmisionAgendadosPorVenir_Result> UspGetDashboardAdmisionAgendadosPorVenir()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetDashboardAdmisionAgendadosPorVenir_Result>("UspGetDashboardAdmisionAgendadosPorVenir");
        }
    
        public virtual ObjectResult<UspGetAdmisionAgendados_Result> UspGetAdmisionAgendados(Nullable<System.DateTime> date)
        {
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetAdmisionAgendados_Result>("UspGetAdmisionAgendados", dateParameter);
        }
    
        public virtual ObjectResult<UspBuscaServicioRegistro_Result> UspBuscaServicioRegistro(Nullable<int> iDfactura)
        {
            var iDfacturaParameter = iDfactura.HasValue ?
                new ObjectParameter("IDfactura", iDfactura) :
                new ObjectParameter("IDfactura", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspBuscaServicioRegistro_Result>("UspBuscaServicioRegistro", iDfacturaParameter);
        }
    
        public virtual int UspPostServicioEntrega(Nullable<int> iDfactura, Nullable<int> iDusuario, Nullable<System.DateTime> fechaEntrega)
        {
            var iDfacturaParameter = iDfactura.HasValue ?
                new ObjectParameter("IDfactura", iDfactura) :
                new ObjectParameter("IDfactura", typeof(int));
    
            var iDusuarioParameter = iDusuario.HasValue ?
                new ObjectParameter("IDusuario", iDusuario) :
                new ObjectParameter("IDusuario", typeof(int));
    
            var fechaEntregaParameter = fechaEntrega.HasValue ?
                new ObjectParameter("FechaEntrega", fechaEntrega) :
                new ObjectParameter("FechaEntrega", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UspPostServicioEntrega", iDfacturaParameter, iDusuarioParameter, fechaEntregaParameter);
        }
    
        public virtual ObjectResult<UspReporteServiciosRegistro_Result> UspReporteServiciosRegistro()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspReporteServiciosRegistro_Result>("UspReporteServiciosRegistro");
        }
    
        public virtual ObjectResult<UspServicioRegistroBusqueda_Result> UspServicioRegistroBusqueda(Nullable<int> iDfactura)
        {
            var iDfacturaParameter = iDfactura.HasValue ?
                new ObjectParameter("IDfactura", iDfactura) :
                new ObjectParameter("IDfactura", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspServicioRegistroBusqueda_Result>("UspServicioRegistroBusqueda", iDfacturaParameter);
        }
    
        public virtual int UspServicioRegistroInserta(Nullable<int> iDfactura, Nullable<int> iDusuario, Nullable<System.DateTime> fechaEntrega, string comentario)
        {
            var iDfacturaParameter = iDfactura.HasValue ?
                new ObjectParameter("IDfactura", iDfactura) :
                new ObjectParameter("IDfactura", typeof(int));
    
            var iDusuarioParameter = iDusuario.HasValue ?
                new ObjectParameter("IDusuario", iDusuario) :
                new ObjectParameter("IDusuario", typeof(int));
    
            var fechaEntregaParameter = fechaEntrega.HasValue ?
                new ObjectParameter("FechaEntrega", fechaEntrega) :
                new ObjectParameter("FechaEntrega", typeof(System.DateTime));
    
            var comentarioParameter = comentario != null ?
                new ObjectParameter("Comentario", comentario) :
                new ObjectParameter("Comentario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UspServicioRegistroInserta", iDfacturaParameter, iDusuarioParameter, fechaEntregaParameter, comentarioParameter);
        }
    
        public virtual ObjectResult<UspServicioRegistroReporteCondicionAcademica_Result> UspServicioRegistroReporteCondicionAcademica(Nullable<int> idPeriodo)
        {
            var idPeriodoParameter = idPeriodo.HasValue ?
                new ObjectParameter("idPeriodo", idPeriodo) :
                new ObjectParameter("idPeriodo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspServicioRegistroReporteCondicionAcademica_Result>("UspServicioRegistroReporteCondicionAcademica", idPeriodoParameter);
        }
    
        public virtual ObjectResult<UspServicioRegistroReporteEntregado_Result> UspServicioRegistroReporteEntregado()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspServicioRegistroReporteEntregado_Result>("UspServicioRegistroReporteEntregado");
        }
    
        public virtual ObjectResult<UspServicioRegistroReporteRangoFecha_Result> UspServicioRegistroReporteRangoFecha(Nullable<System.DateTime> fechaInicial, Nullable<System.DateTime> fechaFinal)
        {
            var fechaInicialParameter = fechaInicial.HasValue ?
                new ObjectParameter("fechaInicial", fechaInicial) :
                new ObjectParameter("fechaInicial", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("fechaFinal", fechaFinal) :
                new ObjectParameter("fechaFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspServicioRegistroReporteRangoFecha_Result>("UspServicioRegistroReporteRangoFecha", fechaInicialParameter, fechaFinalParameter);
        }
    
        public virtual ObjectResult<UspServicioRegistroReporteSolicitado_Result> UspServicioRegistroReporteSolicitado()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspServicioRegistroReporteSolicitado_Result>("UspServicioRegistroReporteSolicitado");
        }
    
        public virtual ObjectResult<UspGetDashboardRegistroCondicionAcademica_Result> UspGetDashboardRegistroCondicionAcademica(Nullable<int> idPeriodo)
        {
            var idPeriodoParameter = idPeriodo.HasValue ?
                new ObjectParameter("idPeriodo", idPeriodo) :
                new ObjectParameter("idPeriodo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetDashboardRegistroCondicionAcademica_Result>("UspGetDashboardRegistroCondicionAcademica", idPeriodoParameter);
        }
    
        public virtual ObjectResult<UspGetDashboardRegistroServicioEntregadoFecha_Result> UspGetDashboardRegistroServicioEntregadoFecha()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetDashboardRegistroServicioEntregadoFecha_Result>("UspGetDashboardRegistroServicioEntregadoFecha");
        }
    
        public virtual ObjectResult<UspGetDashboardRegistroServicioEntregadoTipoServicio_Result> UspGetDashboardRegistroServicioEntregadoTipoServicio()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetDashboardRegistroServicioEntregadoTipoServicio_Result>("UspGetDashboardRegistroServicioEntregadoTipoServicio");
        }
    
        public virtual ObjectResult<UspGetDashboardRegistroServicioEntregadoUsuario_Result> UspGetDashboardRegistroServicioEntregadoUsuario()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetDashboardRegistroServicioEntregadoUsuario_Result>("UspGetDashboardRegistroServicioEntregadoUsuario");
        }
    
        public virtual ObjectResult<UspGetDashboardRegistroServiciosEntregados_Result> UspGetDashboardRegistroServiciosEntregados()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetDashboardRegistroServiciosEntregados_Result>("UspGetDashboardRegistroServiciosEntregados");
        }
    
        public virtual ObjectResult<UspGetDashboardRegistroServiciosSolicitados_Result> UspGetDashboardRegistroServiciosSolicitados()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetDashboardRegistroServiciosSolicitados_Result>("UspGetDashboardRegistroServiciosSolicitados");
        }
    
        public virtual ObjectResult<UspGetServiciosRegistroSolicitados_Result> UspGetServiciosRegistroSolicitados()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetServiciosRegistroSolicitados_Result>("UspGetServiciosRegistroSolicitados");
        }
    
        public virtual ObjectResult<UspReporteInscritosSeleccionXGeneroCuatrimestre_Result> UspReporteInscritosSeleccionXGeneroCuatrimestre(Nullable<int> idPeriodo)
        {
            var idPeriodoParameter = idPeriodo.HasValue ?
                new ObjectParameter("idPeriodo", idPeriodo) :
                new ObjectParameter("idPeriodo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspReporteInscritosSeleccionXGeneroCuatrimestre_Result>("UspReporteInscritosSeleccionXGeneroCuatrimestre", idPeriodoParameter);
        }
    
        public virtual ObjectResult<UspReporteInscritosSeleccionXGeneroNuevosViejosCuatrimestre_Result> UspReporteInscritosSeleccionXGeneroNuevosViejosCuatrimestre(Nullable<int> idPeriodo)
        {
            var idPeriodoParameter = idPeriodo.HasValue ?
                new ObjectParameter("idPeriodo", idPeriodo) :
                new ObjectParameter("idPeriodo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspReporteInscritosSeleccionXGeneroNuevosViejosCuatrimestre_Result>("UspReporteInscritosSeleccionXGeneroNuevosViejosCuatrimestre", idPeriodoParameter);
        }
    
        public virtual ObjectResult<UspReporteInscritosSeleccionXGeneroYCarreraCuatrimestre_Result> UspReporteInscritosSeleccionXGeneroYCarreraCuatrimestre(Nullable<int> idPeriodo)
        {
            var idPeriodoParameter = idPeriodo.HasValue ?
                new ObjectParameter("idPeriodo", idPeriodo) :
                new ObjectParameter("idPeriodo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspReporteInscritosSeleccionXGeneroYCarreraCuatrimestre_Result>("UspReporteInscritosSeleccionXGeneroYCarreraCuatrimestre", idPeriodoParameter);
        }
    
        public virtual ObjectResult<UspReporteInscritosSeleccionXPaisCuatrimestre_Result> UspReporteInscritosSeleccionXPaisCuatrimestre(Nullable<int> idPeriodo)
        {
            var idPeriodoParameter = idPeriodo.HasValue ?
                new ObjectParameter("idPeriodo", idPeriodo) :
                new ObjectParameter("idPeriodo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspReporteInscritosSeleccionXPaisCuatrimestre_Result>("UspReporteInscritosSeleccionXPaisCuatrimestre", idPeriodoParameter);
        }
    
        public virtual ObjectResult<UspReporteInscritosSeleccionXProvinciaCuatrimestre_Result> UspReporteInscritosSeleccionXProvinciaCuatrimestre(Nullable<int> idPeriodo)
        {
            var idPeriodoParameter = idPeriodo.HasValue ?
                new ObjectParameter("idPeriodo", idPeriodo) :
                new ObjectParameter("idPeriodo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspReporteInscritosSeleccionXProvinciaCuatrimestre_Result>("UspReporteInscritosSeleccionXProvinciaCuatrimestre", idPeriodoParameter);
        }
    
        public virtual ObjectResult<UspRegistroParaEnviarCarta_Result> UspRegistroParaEnviarCarta()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspRegistroParaEnviarCarta_Result>("UspRegistroParaEnviarCarta");
        }
    }
}
