//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITLA_PE_MVC.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProyectoEspecialMateriaGrupo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProyectoEspecialMateriaGrupo()
        {
            this.Solicitud = new HashSet<Solicitud>();
        }
    
        public int ProyectoEspecialMateriaGrupoID { get; set; }
        public int ProyectoEspecialID { get; set; }
        public int idMateria { get; set; }
        public int idGrupo { get; set; }
        public bool isActive { get; set; }
        public int SolicitanteCupo { get; set; }
        public int SolicitanteCantidad { get; set; }
        public int AprobacionCupo { get; set; }
        public int AprobacionCantidad { get; set; }
        public string MateriaDescripcion { get; set; }
    
        public virtual ProyectoEspecial ProyectoEspecial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitud> Solicitud { get; set; }
    }
}
