//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITLA_PE_MVC.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProyectoEspecial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProyectoEspecial()
        {
            this.ProyectoEspecialMateriaGrupo = new HashSet<ProyectoEspecialMateriaGrupo>();
        }
    
        public int ProyectoEspecialID { get; set; }
        public System.Guid RowID { get; set; }
        public byte[] RowVersion { get; set; }
        public string ProyectoEspeciaNombre { get; set; }
        public string ProyectoEspecialDescripción { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> FechaAdmisionDesde { get; set; }
        public Nullable<System.DateTime> FechaAdmisionHasta { get; set; }
        public string PrefijoSolicitud { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoEspecialMateriaGrupo> ProyectoEspecialMateriaGrupo { get; set; }
    }
}
