//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITLA_PE_MVC.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Settings
    {
        public int SettingID { get; set; }
        public int DaysToAskForNewPassword { get; set; }
        public string MailServer { get; set; }
        public string MailAccount { get; set; }
        public string MailPassword { get; set; }
        public string MailPort { get; set; }
        public string MailFrom { get; set; }
        public string MailDomain { get; set; }
    }
}
