//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITLA_PE_MVC.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Solicitud()
        {
            this.SolicitudAnexo = new HashSet<SolicitudAnexo>();
        }
    
        public int SolicitudID { get; set; }
        public int ProyectoEspecialMateriaGrupoID { get; set; }
        public Nullable<int> ProyectoEspecialMateriaGrupoIDSegundaOpcion { get; set; }
        public string CodigoSolicitud { get; set; }
        public System.Guid RowID { get; set; }
        public byte[] RowVersion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string Email { get; set; }
        public int GenericID_TipoIdentificacion { get; set; }
        public int GenericID_EstatusSolicitud { get; set; }
        public string IdentificacionCedula { get; set; }
        public string IdentificacionGenerada { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string TelResidencial { get; set; }
        public string TelCelular { get; set; }
        public int DireccionidMunicipio { get; set; }
        public string DireccionCalleNumero { get; set; }
        public int GenericID_NivelAcademico { get; set; }
        public string ResultadoComentario { get; set; }
        public Nullable<int> ProvinciaId { get; set; }
        public Nullable<int> Ingreso_Familiar { get; set; }
        public Nullable<bool> TieneInternet { get; set; }
        public Nullable<bool> TieneLaptopPc { get; set; }
        public Nullable<bool> TieneSubsidio { get; set; }
    
        public virtual ProyectoEspecialMateriaGrupo ProyectoEspecialMateriaGrupo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudAnexo> SolicitudAnexo { get; set; }
    }
}
