//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITLA_PE_MVC.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudAnexo
    {
        public int SolicitudAnexoID { get; set; }
        public int SolicitudID { get; set; }
        public int GenericID_TipoDocumento { get; set; }
        public string ArchivoURL { get; set; }
        public bool IsActive { get; set; }
        public string LocalFile { get; set; }
    
        public virtual Solicitud Solicitud { get; set; }
    }
}
