//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITLA_PE_MVC.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLog
    {
        public int UserLogID { get; set; }
        public int UserID { get; set; }
        public string UserActionCode { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Detail { get; set; }
        public int LoginSessionID { get; set; }
    
        public virtual User User { get; set; }
        public virtual UserAction UserAction { get; set; }
    }
}
